### ISSUE TITLE
Bug: Caret not positioning correctly when not clicking directly on the text

### ISSUE THREAD

**Issue by carlesnunez** [FormidableLabs/use-editable#14]
Hello! First of all, thank you for building such an amazing hook it is being useful!

While my development I've spotted a weird behavior when using it which I'm not sure how to fix. A video would be ten times more useful than words so here you have:

https://user-images.githubusercontent.com/5639972/129219645-1fc81e39-a60a-4aca-a2c7-e21661bdf87c.mp4

I'm not sure why does it happens but is something super annoying for some users. Could you help me?

**Comment by kitten** [comment]
I haven't been able to create a reproduction for this, so I unfortunately do have to ask you whether you can create a quick CodeSandbox that can reproduce this reliably, with some "click instructions". I've been trying all sorts of combinations of selecting, clicking, deselecting, clicking, etc in Firefox and Chrome, and can't quite get it to reproduce this reliably.

**Comment by carlesnunez** [comment]
I have no time right now but during the next days I'll try to reproduce a case in which it happens! Thx for the fast response @kitten

**Comment by carlesnunez** [comment]
I've found a slot to test it. The error occurs when a change is happens on the onClick event of an element. Here you have a case:
https://codesandbox.io/s/use-editable-forked-j9itq?file=/src/Edit.js

And a video with reproduce steps:

https://user-images.githubusercontent.com/5639972/129362316-12d453ef-00a6-4710-9d80-a6f7b2a8ee55.mp4

**Comment by carlesnunez** [comment]
Hello, any updates in this one? cc: @kitten

**Comment by carlesnunez** [comment]
I've been investigating a bit by my own and find out that the problem might be related with this code:
```jsx
  useLayoutEffect(() => {
    state.onChange = onChange;

    if (!elementRef.current || opts!.disabled) return;

    state.disconnected = false;
    state.observer.observe(elementRef.current, observerSettings);
    if (state.position) {
      const { position, extent } = state.position;
      setCurrentRange(
        makeRange(elementRef.current, position, position + extent)
      );
    }

    return () => {
      state.observer.disconnect();
    };
  });
```

Commenting this piece of code makes the bug disappear, but OFC I assume that this is necessary.

cc: @kitten

**Comment by Ontopic** [comment]
Your sandbox seems to be using Slate..?

**Comment by carlesnunez** [comment]
Hello @Ontopic I've fixed the codesandbox, sorry and THX for the heads up!:
https://codesandbox.io/s/use-editable-forked-j9itq?file=/src/Edit.js

**Comment by Ontopic** [comment]
I had a quick look, what I think might be worth exploring is you direct call to setSelection; that rerenders your component (since it changes the useState value). So when you click, it shortly moves the cursor to the right position, but immediately rerenders and "reset" the cursor. Will have a better look later. Let me know if you find anything.

**Comment by Ontopic** [comment]
Couldn't resist quickly trying out not putting select in a useState.

```
import React, { useState, useRef, useCallback } from "react";
import { useEditable } from "use-editable";

export default () => {
  const [txt, setTxt] = useState("Text");
  const editorRef = useRef(null);
  // const [selected, setSelected] = useState(false);
  const status = useRef({
    selected: false
  })
 
  const onEditableChange = useCallback((value) => {
    console.log(`"${value}"`)
    setTxt(value.slice(0, -1))
  }, [])

  const Edit = useEditable(editorRef, onEditableChange, {
    disabled: false,
    indentation: 2
  })

  return (
    <div
      className="App"
      ref={editorRef}
      // onClick={() => setSelected(!selected)}
      onClick={() => (status.current.selected = !status.current.selected)}
      
      style={{ backgroundColor: status.current.selected ? "gray" : "white" }}
    >
      {txt}
    </div>
  );
};
```
This at least fixes your bug, but selection is only shown when rerendered (so after setTxt is called). You can work around this in several ways, but I don't you selected state should not go with a onClick anyway. Trying with onFocus and onBlur would be more stable.

**Comment by carlesnunez** [comment]
I'm pretty sure that this shouldn't happen no matter which implementation do we have. Using a reference to avoid a re-render onClick IMHO is not a realistic solution that scales well. I've been trying older versions of the library and it seems that in previous versions this bug wasn't happening.

**Comment by carlesnunez** [comment]
A pr has been oppened.
